name: MLOps Pipeline with DVC and Dagshub

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install dvc dvc[s3] mlflow

    - name: Pull DVC data from Dagshub
      run: |
        dvc remote modify dagshub --local auth basic
        dvc remote modify dagshub --local user $DAGSHUB_USERNAME
        dvc remote modify dagshub --local password $DAGSHUB_USER_TOKEN
        dvc pull -v

    - name: Reproduce pipeline
      run: dvc repro

    - name: Push updated DVC files + metrics
      run: |
        dvc push
